# Site settings
title: CLI Gem Assessment
header-img: img/home-bg.png
email: joselycas@gmail.com
copyright_name: joselycas
description: > # this means to ignore newlines until "baseurl:"
  The intimidation goes away!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  joselycas
learn_profile: joselycas
email_username: joselycas@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
